language: python

python:
  - "2.7"
  - "3.4"

env:
  - DJANGO_VERSION=1.6.10
  - DJANGO_VERSION=1.7.7
  - DJANGO_VERSION=1.8c1

matrix:
  exclude:
    - python: "3.4"
      env: DJANGO_VERSION=1.6.10

install:
  - "pip install Django==$DJANGO_VERSION"
  - "pip install -r requirements.txt"

script: ./runtests.sh
